Crdcdh 127
CBIIT/crdc-datahub-authn pull request #11
Opened 2023-08-17 12:14 UTC by Wesley-Lau

Added session-til endpoints (/api/auth/session-ttl).

2023-08-17 21:50 UTC, AustinSMueller requested changes

2023-08-17 21:50 UTC, AustinSMueller commented on routes/auth.js
> +            response = {ttl: sessionExpiration.valueOf() - currentTime}
We need to return this time in seconds but I think this currently returns this in milliseconds

2023-08-17 21:50 UTC, AustinSMueller commented on routes/auth.js
The session initialization code is still missing the cookie.maxAge property. This might have been in a submodule change that wasn't included here but not having will always result in the expiration being null in the cookie. Please include a submodule PR to add this

2023-08-17 21:50 UTC, AustinSMueller commented on routes/auth.js
Currently, every time the session-ttl endpoint is hit, the session timeout resets. This endpoint should not affect the session timeout so we need to move it to a different router class and declare it in app.js before the session is created to move it outside of the session scope. 

When making this update can you also move the ping and version endpoints outside of the session scope as well?

Let me know if you have any questions about this and we can discuss, Bento has is implemented this way if you want to look at an example

2023-08-21 17:20 UTC, Wesley-Lau commented
Need to update function to call MongoDB for session expiration time.

2023-08-21 17:20 UTC, closed without merging